### ISSUE TITLE
Increase (hard-coded) transfer steps limit

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/circles-myxogastria#175]
Already sending 50 Circles to someone with multiple steps was "too complex" for app. The current limit is set to max. 5 steps here https://github.com/CirclesUBI/circles-core/blob/main/src/token.js#L8 and needs to be revisited.

We should do some maths to find out which number is actually the limit.

**Some first numbers:**
* 12,500,000 Gas Block Size (https://www.xdaichain.com/for-developers/developer-resources#general-information)
* ca. 50.000 gas per transaction

**Todo:**

- [x] Change value to more fine-grained limit https://github.com/CirclesUBI/circles-core/pull/79
- [x] Add a comment to the constant referring to research https://github.com/CirclesUBI/circles-core/pull/79
- [x] Write about researched values in handbook https://github.com/CirclesUBI/circles-handbook/pull/29
- [ ] Write in circles forum maybe?

**Comment by adzialocha** [comment]
I've increased the hard-coded limit to another higher arbitrary number @louilinn, so other users can test some more complex transactions already.

**Comment by louilinn** [comment]
50 steps with 50,000 gas is 2,500,000 in total. 
I don't know how exact we want to be in determining this number but a factor 5 below the absolute maximum seems reasonable to me. Though I haven't seen transactions being more expensive than around 75,000 gas. With this amount of gas per transaction and 50 transactions it should be really unlikely to go beyond 3,750,000. 

Is there some known parameters affecting the gas? Could it possible be even higher? Does the amount sent matter? Timing? I tried to figure this out but maybe you know more already?
@adzialocha

**Comment by louilinn** [comment]
Handbook updates from findings https://github.com/CirclesUBI/circles-handbook/pull/29

**Comment by louilinn** [comment]
I continued comparing the transfer paths with chriseths pathfinder, at least now I cant find a transfer that requires more than ~40 steps (ours require around 150 steps for the same transaction. Chrisehts pathfinder also finds short paths (7 steps) for sending 400 circles while our pathfinder returns 50+-paths for 120 CRC transfer. See the handbook PR about this. I think this is important to fix.
Digging for one issue and you find something else hehe..
