### ISSUE TITLE
[EPIC] update dashboard layout - buttons

### ISSUE THREAD

**Issue by shorn-gnosis** [CirclesUBI/circles-myxogastria#779]
### Objective:
Modify the layout of the dashboard buttons based on the provided screenshots to prioritise transactions over trusting, and adding a relevant help link for the trust button.
 
### Current Layout:
- Buttons positioned side-by-side ("Trust People" and "Send Circles").
  
### New Layout Requirements:
- Position the buttons ("Send Circles" and "Trust People") vertically, stacked on top of each other.
- Ensure the balance and other elements like usernames and avatars remain the same and are appropriately spaced.
- Add a help link [modal trigger or external link - more info to follow] underneath the "trust people" button.
 
### To do:
- [ ] Change the buttons "Trust People" and "Send Circles" from a horizontal to a vertical stack.
- [ ] - [ ] Increase the button width to maintain consistency in the design.
- [ ] Ensure the buttons are centered.
- [ ] add text as link with content `What does it mean to trust someone?`
  
 ### QA Acceptance Criteria:
 
- [ ] Verify the buttons "Trust People" and "Send Circles" are stacked vertically and centered.
- [ ] Ensure there is sufficient spacing between the avatar, balance, buttons, and other text elements.
- [ ] Confirm the "What does it mean to trust someone?" text is correctly placed under the buttons.
- [ ] Confirm clicking the text link takes the user to the target... TBC
