### ISSUE TITLE
[epic] add profile migration opt-in form

### ISSUE THREAD

**Issue by shorn-gnosis** [CirclesUBI/circles-myxogastria#780]
## Scenario:

We need to transfer all garden profile data from the current servers (owned and maintained by Poetic Tech) to Gnosis (as per the announcement here: https://x.com/CirclesUBI/status/1785305562462494741).
As such we need to request permission from all garden users before any data is moved.

### Background:

"There will be a 3 months migration period where the users will be asked for their consent to migrate their email, username and photo to the new Circles infrastructure. If you accept the migration of your user profile, this will mean that your data will be transferred to the new Circles team. At the end of the migration period, all the data that is not transferred will be deleted from current databases. Your wallet, seed phrase, and CRC will not be deleted, and you will still be able to access to your wallet via [http://circles.garden/](http://circles.garden/)"

## Proposal:

- Add a message to the login page.
- Add content and a form to a new garden page called `profile-migrate` with a link to the Twitter post informing the user about the migration and requesting them to opt-in.
- Add a news item (in-app notification) in circles garden for all logged-in users (who would otherwise not see the msg on the login page) informing them about the migration. 

### Front-end:**
**Login page:**
- [x] Add a text message with the following content: `Circles Garden profile data is being migrated. You can read about this here: <https://x.com/CirclesUBI/status/1785305562462494741`> - (create short link using [[bit.ly](http://bit.ly/)](http://bit.ly/) or alternative)
- [x] Add the message: Please login and visit the 'profile-migrate' page to confirm your preference
- [x] suggested position: underneath the signup / login buttons

**Dashboard page:**
- [x] Add a text message with the following content: `Circles Garden profile data is being migrated. You can read about this here: <https://x.com/CirclesUBI/status/1785305562462494741`> - (create short link using [[bit.ly](http://bit.ly/)](http://bit.ly/) or alternative)
- [x] Add the message: Please visit the 'profile-migrate' page to confirm your preference
- [x] suggested position: underneath the balance display - above the button group

**Publish a news item:**
- [ ] Publish a new news item with the following content: `Circles Garden profile data is being migrated. You can read about this here: <https://x.com/CirclesUBI/status/1785305562462494741`> - (create short link using [[bit.ly](http://bit.ly/)](http://bit.ly/) or alternative)
- [ ] Add the message: Please visit the 'profile-migrate' page to confirm your preference.

**Profile migrate page:**
- [x] create a new page at `profile-migrate`
- [x] add a title `Migrate Your Profile`
- [x] add a text paragraph (with placeholder text for now)
- [x] display radio buttons with the label: `Do you consent to the migration of your profile data to the new Circles team?
- [x] option 1 : `No` (default)
- [x] option 2: `Yes`
- [x] `Submit` button
- [x] display a submission confirmation message: [TBD]

NOTE: it is important that we clearly explain the difference between profile data and an account (ie: editable database info vs blockchain)

**Back-end:**
- [ ]  add a database flag that stores the consent option for each user - at the end of August we will export the database but only for users that have answered `yes` to the consent question.

**Comment by mikozet** [comment]
Hi,

I have few concerns. First, it is not obvious for user that after login he made a decision about consent. So If you really opt for solution the way it is presented I would add a text sth like: "By login in you make a decision about your data"

Second: there is no solution for users who want to login but they do not want to make their decision during login time. There is no information for those users that they will be able to do it later and how they can do it. Also users who made a decision are not able to change it.
I also believe that if you care about receiving this data it is not wise to ask users to logout and login again to make a decision. As a lot of users will be simple to lazy to do that as it requires an effort with dealing with seed phrase.

I would suggest to add a new view with proper information where user can decide. It can be done as well in settings page.
Login info could stay so users who visit login page but will not login in due to various reasons are aware of situation.
Text in login page could suggest that in order to make a data decision you need to login and go to 'x' page.

**Comment by shrn-werk** [comment]
thanks for the call earlier @mikozet and @llunaCreixent 

I've updated the ticket based on our discussion and let me know if you have any further suggestions!

do we want to allow users to change their response after the first form submission? If not, we can hide the form, but if yes, we can allow multiple form submissions, each one just updates the db flag... thoughts?

**Comment by mikozet** [comment]
> do we want to allow users to change their response after the first form submission? If not, we can hide the form, but if yes, we can allow multiple form submissions, each one just updates the db flag... thoughts?

definitely I would allow them to change response as if they want to change their mind later and they cannot they may write to you causing additional work..
